server:
  port: 8080
  servlet:
    contextPath: /api


application:
  swagger:
    default-include-pattern: /(?!(error|actuator)).*
    title: CatMash API
    description: CatMash API Documentation
    version: 0.0.1
    terms-of-service-url:
    contact-name:
    contact-url:
    contact-email:
    license:
    license-url: